### ISSUE TITLE
Does not work with Chrome 42 and OS X 10.10.3

### ISSUE THREAD

**Issue by demosthenesameliuslocke** [mathcolo/RadonChrome#1]
The RadonChrome 1.0 bundle downloaded from Github does not work when installed with EasySIMBL and Chrome 42.0.2311.22 and OS X 10.10.3 Public Beta.

**Comment by mathcolo** [comment]
I'll investigate this, thank you!

**Comment by lqkme2** [comment]
Version 41.0.2272.89 (64-bit) and 10.10.3 (14D98g) works perfect!

**Comment by mathcolo** [comment]
As of the 10.10.3 GM today, the extension seems to be working with both Chrome 41 and Chrome 44. Are you still having issues?
