### ISSUE TITLE
Support notifications with buttons?

### ISSUE THREAD

**Issue by cowboy** [mathcolo/RadonChrome#2]
Great project! Is there any way for this to support notifications with buttons?

Buttons might specific to the [chrome.notifications API](https://developer.chrome.com/extensions/notifications) and not standard, but seeing as this is project is intended for Chrome notifications and Chrome notifications can have buttons, it might be a good idea to support them.

Here's some [sample notification-with-button JavaScript](http://stackoverflow.com/a/20190702), in case it helps.

**Comment by mathcolo** [comment]
Chances are it's possible—thanks for the suggestion. I'm a bit busy at the moment but I'll investigate when I can!
